### ISSUE TITLE
Typo "import"/"important"

### ISSUE THREAD

**Issue by apostlkpl** [MicrosoftDocs/linux#14]
There's a typo in the paragraph where you guys explain how to IMPORT (text says "important" instead) a custom distro on WSL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Version Independent ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Content: [How to download and install Linux](https://learn.microsoft.com/en-us/linux/install)
* Content Source: [docs/install.md](https://github.com/MicrosoftDocs/linux/blob/main/docs/install.md)
* Service: **linux-resources**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Doh! Thanks for catching this! Fixing it now. :)
