### ISSUE TITLE
Page is midleasing about dual boot

### ISSUE THREAD

**Issue by znmeb** [MicrosoftDocs/linux#22]
Some Linux distros cannot be installed without disabling both Secure Boot and, on Intel PCs, Intel's Optane(tm) disk speed enhancement technology. At the very least, you should warn potential dual-boot users about this problem, and better yet, list Linux distros that Microsoft supports for dual-booting without disabling Secure Boot. Optane is Intel's problem though.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Version Independent ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Content: [How to download and install Linux](https://learn.microsoft.com/en-us/linux/install)
* Content Source: [docs/install.md](https://github.com/MicrosoftDocs/linux/blob/main/docs/install.md)
* Service: **linux-resources**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by ringoz** [comment]
btw, what Linux distros are Secure Boot ready?
Ubuntu and Fedora only?

**Comment by nikobojs** [comment]
Then I think they should also warn that WSL 2 does not work with all Linux software, and windows updates from time to time will reset your dual boot setup... This smells like a really serious embrace extend extinguish situation. I hope I am wrong...

**Comment by mattwojo** [comment]
Thanks! Added a note about Secure Boot - good call out! This page is not going to get into tracking what Linux distros support or don't support Secure Boot. That's an evolving story and will require checking with the particular distro.
Same for WSL, most distros can be [imported to work with WSL](https://learn.microsoft.com/windows/wsl/use-custom-distro) based on my understanding, but there are so many different distros out there, it's really up to the maintainers to determine what they're going to support.

Resolved in https://github.com/MicrosoftDocs/linux/pull/30/commits/5ac8fe79c8f7a26a24e156a93eaac5d9523f75ee
