### ISSUE TITLE
Typo in VM section of the document

### ISSUE THREAD

**Issue by huddeldaddel** [MicrosoftDocs/linux#24]
In the VM section of the document you can find this text "hardware.There". This is a typo.
It should be "hardware. There".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Version Independent ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Content: [How to download and install Linux](https://learn.microsoft.com/en-us/linux/install)
* Content Source: [docs/install.md](https://github.com/MicrosoftDocs/linux/blob/main/docs/install.md)
* Service: **linux-resources**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks! Fixed in https://github.com/MicrosoftDocs/linux/commit/845a26c7bf4308b1d3683ad945791778f3d445d2
