### ISSUE TITLE
Brian Bruce

### ISSUE THREAD

**Issue by Briantopazbruce** [MicrosoftDocs/linux#29]
Having gotten over a slight surprise (Microsoft giving viable OS alternatives) I realized over the years-last two years in particular, Microsoft has drastically relaxed it's attitudes & outlooks at FOSSs & Open Sources. 

Cheers and Bravos to All at Microsoft. The bottom line as I see it:

    In Software, provide what's wanted while focusing
    on income alternatives to fill a portion of the void
    software has left and will leave at Microsoft as
    Microsoft delves further into the world of FOSS. 

I mean, look to Google that provides all manner of free applications-not to mention SDKs-that run on all manner of platforms including their Cloud & Container lines. Now there exists paid Google Services but Google's real income is generated by its Advertising Campaigns and all the Ad Specifics: tracking, user behaviors, analytics and the like... 

Granted, Google discovered a niche and having faith, I therefor believe Microsoft can bum} into one also. 

Share a personal secret and belief related to the Mobile Telephone industry. 
My Imagination as wild as it can be may be outta there but here goes:

Just how did Google Really come up with the name Android to launch and Market what is arguably the most well-known and well-used OS the world may ever use?

Simple!
    Had they shared that it is actually a security enhanced
    subset of linux, people-at the time of release-would
    have been turned off & run from this technology be-
    cause of the bad reputation Linux has:

        "Linux, oh yeah that's the hackers tool of choice." 

I dare say that Android in a name was the most brilliant rebranding I've ever seen pulled off. 

Told you, my imagination can run off & get away. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Version Independent ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Content: [How to download and install Linux](https://learn.microsoft.com/en-us/linux/install)
* Content Source: [docs/install.md](https://github.com/MicrosoftDocs/linux/blob/main/docs/install.md)
* Service: **linux-resources**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for sharing your thoughts! Don't see any doc updates requested, so closing this as an issue in need of resolution.
