### ISSUE TITLE
Two TOCs listed in the article

### ISSUE THREAD

**Issue by adegeo** [MicrosoftDocs/linux#36]
Because of how the article now lists the TOC at the top, this article has two sets of TOCs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17dea64f-a9cd-c27f-0838-74ee3752ad80
* Version Independent ID: 17dea64f-a9cd-c27f-0838-74ee3752ad80
* Content: [Linux Software Repository for Microsoft Products](https://learn.microsoft.com/en-us/linux/packages)
* Content Source: [docs/packages.md](https://github.com/MicrosoftDocs/linux/blob/main/docs/packages.md)
* Service: **linux-resources**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @adegeo! Do you mean the "In this article" links? If so, I see what you mean -- removed in  https://github.com/MicrosoftDocs/linux/pull/37. Thanks for filing this. :)
