### ISSUE TITLE
Removal of USB drive when wantign to run linux from thier computer

### ISSUE THREAD

**Issue by Kr1s1e** [MicrosoftDocs/linux#38]
I know the tutorila goes over making a bootable USB drive, but you do also mention partitions and running linux as the sole os on the system and I think you should include that you HAVE to remove the USB drive after instillation and during the reboot otherwise you wont be able to run linux at all without the drive. This small piece of information was left out and made me have to rest 2 hours of progress because I couldn't run the OS without the drive and I had to start from scratch. Other than that great article!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Version Independent ID: 88c62beb-c8d0-7960-19bb-585ad26aabd8
* Content: [How to download and install Linux](https://learn.microsoft.com/en-us/linux/install)
* Content Source: [docs/install.md](https://github.com/MicrosoftDocs/linux/blob/main/docs/install.md)
* Service: **linux-resources**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Oh shoot! I'm so sorry that you got hung up on this @Kr1s1e. That's a good call out. I'll get it added in so hopefully others won't experience the same frustration.
